# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-25 11:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('url', models.CharField(blank=True, max_length=100, null=True)),
                ('header', models.CharField(blank=True, max_length=255, null=True)),
                ('boby', models.CharField(blank=True, max_length=10000, null=True)),
                ('cookies', models.CharField(blank=True, max_length=255, null=True)),
                ('remark', models.CharField(blank=True, max_length=100, null=True)),
                ('expect', models.CharField(blank=True, max_length=100, null=True)),
                ('retId', models.CharField(max_length=20, null=True)),
            ],
            options={
                'ordering': ('name',),
                'verbose_name': 'Case',
                'verbose_name_plural': 'Case',
            },
        ),
        migrations.CreateModel(
            name='Flow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('cards', models.CharField(blank=True, max_length=10000, null=True)),
                ('flowRemark', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caseId', models.IntegerField(default=10)),
                ('resultall', models.CharField(max_length=1000, null=True)),
                ('resultId', models.CharField(max_length=50, null=True)),
                ('ret', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Suite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('casesuite', models.CharField(max_length=50, null=True)),
                ('flowId', models.IntegerField(default=10)),
            ],
        ),
    ]
