# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-15 07:39
from __future__ import unicode_literals

import backend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auth_authscript1'),
    ]

    operations = [
        migrations.AddField(
            model_name='authscript1',
            name='jar_pkg',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=backend.models.upload_to, verbose_name='jar\u5305'),
        ),
    ]
