# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-15 08:34
from __future__ import unicode_literals

import backend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_authscript1_jar_pkg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authscript1',
            name='jar_pkg',
        ),
        migrations.AlterField(
            model_name='authscript1',
            name='auth_file',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=backend.models.upload_to, verbose_name='jar\u5305'),
        ),
    ]
