# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-15 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20170515_0834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authscript1',
            name='auth_file',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
