# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-16 03:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20170515_1319'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authscript1',
            old_name='auth_file',
            new_name='auth_jar',
        ),
        migrations.RenameField(
            model_name='authscript1',
            old_name='auth_name',
            new_name='name',
        ),
    ]
