# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-17 07:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_auto_20170516_0316'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag', models.CharField(max_length=10)),
                ('execute_time', models.CharField(max_length=200)),
                ('frikcy', models.IntegerField(default=10)),
                ('unit', models.CharField(max_length=10)),
                ('cases_id', models.CharField(max_length=100)),
                ('switch', models.BooleanField(default=True)),
            ],
        ),
    ]
