# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-17 07:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='unit',
        ),
    ]
