# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-17 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_plan_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='create_time',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
