# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-17 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_plan_create_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='execute_time',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
