# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-21 15:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djcelery', '0001_initial'),
        ('backend', '0011_auto_20170517_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='period',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='djcelery.PeriodicTask', verbose_name='PeriodicTask'),
        ),
    ]
